export const CART_ACTION_TYPES = {
  TOGGLE_CART_SHOW: "TOGGLE_CART_SHOW",
  ADD_ITEM: "ADD_ITEM",
  REDUCE_ITEM_QUANTITY: "REDUCE_ITEM_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
};
